# Generated by Django 5.1.7 on 2025-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KidTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("교육지원청명", models.TextField(blank=True, null=True)),
                ("유치원명", models.TextField(blank=True, null=True)),
                ("설립유형", models.TextField(blank=True, null=True)),
                ("원장명", models.TextField(blank=True, null=True)),
                ("설립일", models.IntegerField(blank=True, null=True)),
                ("개원일", models.IntegerField(blank=True, null=True)),
                ("주소", models.TextField(blank=True, null=True)),
                ("전화번호", models.TextField(blank=True, null=True)),
                ("홈페이지", models.TextField(blank=True, null=True)),
                ("운영시간", models.TextField(blank=True, null=True)),
                ("만3세유아수", models.IntegerField(blank=True, null=True)),
                ("만4세유아수", models.IntegerField(blank=True, null=True)),
                ("만5세유아수", models.IntegerField(blank=True, null=True)),
                ("혼합유아수", models.IntegerField(blank=True, null=True)),
                ("특수유아수", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "kid_table",
                "managed": False,
            },
        ),
    ]
