# Generated by Django 5.2 on 2025-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='유사한야경명소',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.TextField(blank=True, null=True)),
                ('추천1', models.TextField(blank=True, null=True)),
                ('추천2', models.TextField(blank=True, null=True)),
                ('추천3', models.TextField(blank=True, null=True)),
                ('추천4', models.TextField(blank=True, null=True)),
                ('추천5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'similar_night_place',
                'managed': False,
            },
        ),
    ]
