# Generated by Django 5.1.7 on 2025-03-28 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KidTable",
        ),
    ]
