# Generated by Django 5.1.7 on 2025-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="관광거리",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("키", models.TextField(blank=True, null=True)),
                ("검색키워드", models.TextField(blank=True, null=True)),
                ("alias", models.TextField(blank=True, null=True)),
                ("최종표기명", models.TextField(blank=True, null=True)),
                ("지번주소", models.TextField(blank=True, null=True)),
                ("행정시", models.TextField(blank=True, null=True)),
                ("행정구", models.TextField(blank=True, null=True)),
                ("행정동", models.TextField(blank=True, null=True)),
                ("중심좌표X", models.FloatField(blank=True, null=True)),
                ("중심좌표Y", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "tourist_street_table",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="tourist_street_table",
        ),
    ]
