# Generated by Django 5.1.7 on 2025-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_관광거리_delete_tourist_street_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="문화행사",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("분류", models.TextField(blank=True, null=True)),
                ("자치구", models.TextField(blank=True, null=True)),
                ("행사명", models.TextField(blank=True, null=True)),
                ("날짜", models.TextField(blank=True, null=True)),
                ("장소", models.TextField(blank=True, null=True)),
                ("기관명", models.TextField(blank=True, null=True)),
                ("이용대상", models.TextField(blank=True, null=True)),
                ("이용요금", models.TextField(blank=True, null=True)),
                ("대표이미지", models.TextField(blank=True, null=True)),
                ("위도Y좌표", models.FloatField(blank=True, null=True)),
                ("경도X좌표", models.FloatField(blank=True, null=True)),
                ("유무료", models.TextField(blank=True, null=True)),
                ("문화포털상세URL", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cultural_event_table",
                "managed": False,
            },
        ),
    ]
