# Generated by Django 5.1.7 on 2025-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_문화행사"),
    ]

    operations = [
        migrations.CreateModel(
            name="문화공간",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("주제분류", models.TextField(blank=True, null=True)),
                ("문화시설명", models.TextField(blank=True, null=True)),
                ("주소", models.TextField(blank=True, null=True)),
                ("위도", models.FloatField(blank=True, null=True)),
                ("경도", models.FloatField(blank=True, null=True)),
                ("전화번호", models.TextField(blank=True, null=True)),
                ("홈페이지", models.TextField(blank=True, null=True)),
                ("관람시간", models.TextField(blank=True, null=True)),
                ("관람료", models.TextField(blank=True, null=True)),
                ("휴관일", models.TextField(blank=True, null=True)),
                ("객석수", models.TextField(blank=True, null=True)),
                ("대표이미지", models.TextField(blank=True, null=True)),
                ("기타사항", models.TextField(blank=True, null=True)),
                ("시설소개", models.TextField(blank=True, null=True)),
                ("무료구분", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cultural_space_table",
                "managed": False,
            },
        ),
    ]
