# Generated by Django 5.1.7 on 2025-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="district",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
