# Generated by Django 5.1.7 on 2025-04-08 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_userprofile_district_alter_userprofile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
