# Generated by Django 5.1.7 on 2025-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
